# Generated by Django 5.2.5 on 2025-08-14 11:07

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('banking_finance', 'Banking & Finance'), ('transportation', 'Transportation'), ('documentation', 'Documentation'), ('housing', 'Housing & Accommodation'), ('healthcare', 'Healthcare'), ('business', 'Business & Legal'), ('cultural', 'Cultural Integration'), ('emergency', 'Emergency Services')], max_length=30)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='guides/images/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
                'ordering': ['-publication_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country_code', models.CharField(default='+998', max_length=5)),
                ('services_needed', models.JSONField(help_text='List of selected services with their prices')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_budget', models.CharField(blank=True, max_length=50, null=True)),
                ('detailed_requirements', models.TextField(help_text='Detailed description of requirements')),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reviewer_country', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewer_avatar', models.ImageField(blank=True, null=True, upload_to='reviews/avatars/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(max_length=1000)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_used', models.CharField(blank=True, choices=[('wi_fi_sim_setup', 'Wi-Fi & SIM Setup'), ('apartment_finding', 'Apartment Finding'), ('grocery_help', 'Grocery Help'), ('translation_services', 'Translation Services'), ('bill_payments', 'Bill Payments'), ('transportation_help', 'Transportation Help'), ('document_assistance', 'Document Assistance'), ('social_integration', 'Social Integration'), ('business_support', 'Business Support'), ('healthcare_navigation', 'Healthcare Navigation'), ('food_dining', 'Food & Dining'), ('customs_request', 'Customs Request')], max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed guide content with rich text formatting')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='helper.guide')),
            ],
            options={
                'verbose_name': 'Guide Translation',
                'db_table': 'helper_guide_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
